//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIDynamicKeyColumn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.ProductShippers = new HashSet<ProductShipper>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<ProductShipper> ProductShippers { get; set; }
    }
}
