//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIDynamicKeyColumn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public Shipper()
        {
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.ProductShippers = new HashSet<ProductShipper>();
        }
    
        public int ShipperID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<ProductShipper> ProductShippers { get; set; }
    }
}
